import math

def generate_torus(filename, R, r, u_segments, v_segments):
    vertices = []
    faces = []

    for i in range(u_segments):
        u = 2.0 * math.pi * i / u_segments
        for j in range(v_segments):
            v = 2.0 * math.pi * j / v_segments

            x = (R + r * math.cos(v)) * math.cos(u)
            y = (R + r * math.cos(v)) * math.sin(u)
            z = r * math.sin(v)
            vertices.append((x, y, z))

    for i in range(u_segments):
        for j in range(v_segments):
            next_i = (i + 1) % u_segments
            next_j = (j + 1) % v_segments

            v0 = i * v_segments + j + 1
            v1 = next_i * v_segments + j + 1
            v2 = next_i * v_segments + next_j + 1
            v3 = i * v_segments + next_j + 1

            # Two triangles per quad
            faces.append((v0, v1, v2))
            faces.append((v0, v2, v3))

    with open(filename, 'w') as f:
        f.write("# Torus generated by Python\n")
        for v in vertices:
            f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")
        for face in faces:
            f.write(f"f {face[0]} {face[1]} {face[2]}\n")

if __name__ == "__main__":
    generate_torus("torus.obj", R=50.0, r=15.0, u_segments=48, v_segments=24)
    print("torus.obj created successfully.")
